export default {
  GOOGLE_MAPS_API_KEY: process.env.REACT_APP_GOOGLE_MAPS_API_KEY,
  APPLE_MAPS_TOKEN: process.env.REACT_APP_APPLE_MAPS_TOKEN,
  AWS_BUCKET_NAME: process.env.REACT_APP_AWS_BUCKET_NAME,
  AWS_ACCESS_KEY_ID: process.env.REACT_APP_AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.REACT_APP_AWS_SECRET_ACCESS_KEY,
  IMAGES_URL: `https://${process.env.REACT_APP_AWS_BUCKET_NAME}.nyc3.cdn.digitaloceanspaces.com/uploads`,
  // https://urbanapplausedev.nyc3.cdn.digitaloceanspaces.com/uploads/24af45e0-0c68-11ea-99ea-7fe7b8110c7d
  //SERVER URLS
  SERVER_URL: process.env.NODE_ENV=="development" ? "http://localhost:8080" : "https://api.urbanapplause.com",
  UPLOADS_SUBPATH: "api/uploads",

 // AUTH ACTIONS
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  REGISTER_RESET: "REGISTER_RESET",
  LOGIN_RESET: "LOGIN_RESET",


  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER_RESET: "REGISTER_RESET",
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
  AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

  // WORK ACTIONS
  SET_NEW_FILES: "SET_NEW_FILES",
  AWAIT_IMAGE_UPLOAD_RESPONSE: "AWAIT_IMAGE_UPLOAD_RESPONSE",
  IMAGE_UPLOAD_SUCCESS: "IMAGE_UPLOAD_SUCCESS",

  REQUEST_WORKS_DATA: "REQUEST_WORKS_DATA",
  RECEIVE_WORKS_DATA: "RECEIVE_WORKS_DATA",
  WORKS_DATA_ERROR: "WORKS_DATA_ERROR",

  REQUEST_WORK_DATA: "REQUEST_WORK_DATA",
	RECEIVE_WORK_DATA: "RECEIVE_WORK_DATA",
	AWAIT_NEW_WORK_RESPONSE: "AWAIT_NEW_WORK_RESPONSE",
  RECEIVE_NEW_WORK_RESPONSE: "RECEIVE_NEW_WORK_RESPONSE",

	FAILED_NEW_WORK_RESPONSE: "FAILED_NEW_WORK_RESPONSE",
	START_WORK_EDIT: "START_WORK_EDIT",
	FINISH_WORK_EDIT: "FINISH_WORK_EDIT",
  SUBMIT_WORK_EDIT: "SUBMIT_WORK_EDIT",

  // COMMENT ACTIONS

  REQUEST_COMMENTS_DATA: "REQUEST_COMMENTS_DATA",
  RECEIVE_COMMENTS_DATA: "RECEIVE_COMMENTS_DATA",

	AWAIT_NEW_COMMENT_RESPONSE: "AWAIT_NEW_COMMENT_RESPONSE",
  RECEIVE_NEW_COMMENT_RESPONSE: "RECEIVE_NEW_COMMENT_RESPONSE",
  FAILED_NEW_COMMENT_RESPONSE: "FAILED_NEW_COMMENT_RESPONSE",

	START_COMMENT_EDIT: "START_COMMENT_EDIT",
	FINISH_COMMENT_EDIT: "FINISH_COMMENT_EDIT",
  SUBMIT_COMMENT_EDIT: "SUBMIT_COMMENT_EDIT",

  // ARTIST ACTIONS
  REQUEST_ARTISTS_DATA: "REQUEST_ARTISTS_DATA",
  RECEIVE_ARTISTS_DATA: "RECEIVE_ARTISTS_DATA",

  REQUEST_ARTIST_DATA: "REQUEST_ARTIST_DATA",
  RECEIVE_ARTIST_DATA: "RECEIVE_ARTIST_DATA",
	AWAIT_NEW_ARTIST_RESPONSE: "AWAIT_NEW_ARTIST_RESPONSE",
	RECEIVE_NEW_ARTIST_RESPONSE: "RECEIVE_NEW_ARTIST_RESPONSE",
	START_ARTIST_EDIT: "START_ARTIST_EDIT",
  ARTIST_EDIT_ERROR: "ARTIST_EDIT_ERROR",
	ARITST_EDIT_SUCCESS: "ARTIST_EDIT_SUCCESS",

  //USER ACTIONS
  //
  REQUEST_USERS_DATA: "REQUEST_USERS_DATA",
  RECEIVE_USERS_DATA: "RECEIVE_USERS_DATA",
  REQUEST_USER_DATA: "REQUEST_USER_DATA",
	RECEIVE_USER_DATA: "RECEIVE_USER_DATA",
	AWAIT_NEW_USER_RESPONSE: "AWAIT_NEW_USER_RESPONSE",
	RECEIVE_NEW_USER_RESPONSE: "RECEIVE_NEW_USER_RESPONSE",
	START_USER_EDIT: "START_USER_EDIT",
	FINISH_USER_EDIT: "FINISH_USER_EDIT",
  SUBMIT_USER_EDIT: "SUBMIT_USER_EDIT",

  };


